theme: jekyll-theme-slate
title: Dries Cronje
description: My Web Presence

footer-links:
  github: https://github.com/chasingbob
  twitter: https://twitter.com/dries139
  googleplus: https://plus.google.com/collection/YewGx
